transport:
  name: tcp
  options:
    host: 127.0.0.1
    port: 12345
    max_connections: 1

global:
  cell:
    - [99999.0, 0, 0]
    - [0, 99999.0, 0]
    - [0, 0, 99999.0]
  elements:
    - Si
    - O
  influence_distance: 6.0
